### PR TITLE
Enhanced Jira integration to support filtering by components in JQL queries

### PR DESCRIPTION
**Pull request by SaachiNayyer**
### Describe your changes

Updated the getIssuesByFilter function to accept an array of components,
enabling the construction of more flexible JQL queries. 
Introduced a new variable named componentQuery to represent the portion of the JQL query related to components. 

Enhanced the getIssuesFromFilters function to include support for filtering by components. 
Now, along with project keys and filters, the function also accepts an array of components. 
This change allows for more comprehensive filtering options when retrieving issues from Jira.

Modified the router implementation to pass the array of components to the getIssuesFromFilters function. 
By including components in the request, users can now specify additional criteria for filtering Jira issues, 
resulting in more refined search results.

The introduced changes provide users with greater flexibility and control when retrieving Jira issues, 
allowing for more precise filtering based on project keys, components, and filter criteria. 
This enhancement improves the overall usability and effectiveness of the Jira integration functionality.
### Issue ticket number and link

- Fixes #(issue)

### Checklist before requesting a review

- [X] I have performed a self-review of my own code
- [X] I have verified that the code builds perfectly fine on my local system
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have verified that my code follows the style already available in the repository
- [X] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by anicke** [comment]
This PR needs to rebased? There's parts of the last one in this?

**Comment by SaachiNayyer** [comment]
> This PR needs to rebased? There's parts of the last one in this?

Done

**Comment by SaachiNayyer** [comment]
Hi [anicke](https://github.com/anicke)
Is there any update for this PR
Thanks

**Review by anicke — APPROVED** [review]
Thank you!

**Pull request merged**
