### PR TITLE
Jira Dashboard Table/Card - support for tableOptions

### PR DESCRIPTION
**Pull request by Vity01**
### Context

Most of cards on the homepage follows the rule that the Title is part of InfoCard and the content is stretched, which is not easily possible with current setup. 
Also probably most of users won't need to use filter search functionality on the homepage and it takes free space. 
Note, it does not make influence to the dashboard page, just the homepage.

**Before:**
image

**After:**
image

### Issue ticket number and link

- Fixes # (issue)

### Checklist before requesting a review

- [x] I have performed a self-review of my own code
- [x] I have verified that the code builds perfectly fine on my local system
- [x] I have verified that my code follows the style already available in the repository
- [x] A changeset describing the change and affected packages. ([more info](https://github.com/AxisCommunications/backstage-plugins/blob/main/CONTRIBUTING.md#changesets))
- [x] Added or updated documentation
- [x] Tests for new functionality and regression tests for bug fixes
- [x] Screenshots attached (for UI changes)

### CODE REVIEW

**Comment by Vity01** [comment]
Anyone?

**Comment by fridajac** [comment]
> Anyone?

Nice! Will have a look at it as soon as we can :+1:

**Review by anicke — APPROVED** [review]
Thank you!

**Comment by Vity01** [comment]
Thank you :-)

**Pull request merged**
