### PR TITLE
Improved Jira-Dashboard APIs

### LINKED ISSUE #76: [BUG] entityRef path parameter is encoding a reserved delimiter character
> **Please do not disclose security vulnerabilities as issues. See our [security policy](../../SECURITY.md) for responsible disclosures.**

### Describe the bug

when it is deployed behind my auth proxy service, the /:entityref path parameter gets decoded and then the backend fails to find a matching URI path. This is what happens:

UI fetches:
`/api/jira-dashboard/avatar/by-entity-ref/component%3Adefault%2Fexample-website`

Backend URI received:
`/api/jira-dashboard/avatar/by-entity-ref/component:default/example-website`

so express is trying to match a route for something like the below APIs, but can't find it and responds with a 404:
/api/jira-dashboard/avatar/by-entity-ref/:entityref/example-website
/api/jira-dashboard/avatar/by-entity-ref/:entityref/:name

where ":entityref == "component:default"

Technically speaking, RFC3986 section 2.2 explains the risks of encoding reserved characters such as '/' in the URI path:

> The purpose of reserved characters is to provide a set of delimiting
   characters that are distinguishable from other data within a URI.
   URIs that differ in the replacement of a reserved character with its
   corresponding percent-encoded octet are not equivalent.  Percent-
   encoding a reserved character, or decoding a percent-encoded octet
   that corresponds to a reserved character, will change how the URI is
   interpreted by most applications.

Reference:
https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

### To reproduce

1. Setup backstage to use the oauth2Proxy sign on provider as such:
https://backstage.io/docs/auth/oauth2-proxy/provider

2. startup oauth2Proxy such as this example docker-compose file: https://github.com/backstage/backstage/blob/57397e7d6d2d725712c439f4ab93f2ac6aa27bf8/plugins/auth-backend/examples/docker-compose.oauth2-proxy.yaml

3. add jira-dashboard plugins to the backstage app.

4. Navigate to the jira-dashboard tab of a valid entity.

5. Jira tab shows "404" error, where UI fetches:
`/api/jira-dashboard/avatar/by-entity-ref/component%3Adefault%2Fexample-website`

Backend URI received:
`/api/jira-dashboard/avatar/by-entity-ref/component:default/example-website`

### Environment

- Node 18.16.1
- React 18
- custom auth proxy, but can be tested with the oauth2Proxy

### PR DESCRIPTION
**Pull request by aaronnickovich**
### Describe your changes

The plugin works great locally and a huge improvement over Roadie's plugin, but when it is deployed behind my auth proxy service, the /:entityref path parameter gets decoded and then the backend fails to find a matching URI path. This is what happens:

UI fetches:
`/api/jira-dashboard/avatar/by-entity-ref/component%3Adefault%2Fexample-website`

Backend URI received:
`/api/jira-dashboard/avatar/by-entity-ref/component:default/example-website`

so express is trying to match a route for something like the below APIs, but can't find it and responds with a 404:
/api/jira-dashboard/avatar/by-entity-ref/:entityref/example-website
/api/jira-dashboard/avatar/by-entity-ref/:entityref/:name

where ":entityref == "component:default"

Technically speaking, RFC3986 section 2.2 explains the risks of encoding reserved characters such as '/' in the URI path:

> The purpose of reserved characters is to provide a set of delimiting
   characters that are distinguishable from other data within a URI.
   URIs that differ in the replacement of a reserved character with its
   corresponding percent-encoded octet are not equivalent.  Percent-
   encoding a reserved character, or decoding a percent-encoded octet
   that corresponds to a reserved character, will change how the URI is
   interpreted by most applications.

Reference:
https://datatracker.ietf.org/doc/html/rfc3986#section-2.2

proof this works on my install:
Screenshot 2024-02-11 at 1 02 07 AM
Screenshot 2024-02-11 at 1 03 23 AM

### Issue

fixes #76 

### Checklist before requesting a review

- [X] I have performed a self-review of my own code
- [X] I have verified that the code builds perfectly fine on my local system
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have verified that my code follows the style already available in the repository
- [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by anicke** [comment]
Nice, thank you! 

Since there is an additional dependency you need to run `yarn install` and add the updated lock file? We also need a changeset for the affected packages. Run `yarn changeset` and create minor updates for `plugin-jira-dashboard-backend` and `plugin-jira-dashboard`.

**Comment by aaronnickovich** [comment]
> Nice, thank you!
> 
> Since there is an additional dependency you need to run `yarn install` and add the updated lock file? We also need a changeset for the affected packages. Run `yarn changeset` and create minor updates for `plugin-jira-dashboard-backend` and `plugin-jira-dashboard`.

Of course! Thank you for the reminder and being open to change. I will make an update soon

**Comment by aaronnickovich** [comment]
Ready for review!

**Review by fridajac — APPROVED** [review]
Looking good! Thanks! :+1:

**Review by fridajac — CHANGES_REQUESTED** [review]
There seems to be some prettier issues. Please run yarn prettier:fix :)

**Comment by aaronnickovich** [comment]
> There seems to be some prettier issues. Please run yarn prettier:fix :)

Done.

**Review by GLundh — APPROVED** [review]
The prettier issue seems fixed. Though letting Frida taking a final look.

**Review by fridajac — APPROVED** [review]

**Pull request merged**
